<?php
class ChemicalBasic {
	public $id="" ; //int(11) NOT NULL AUTO_INCREMENT COMMENT '序号，无实际意义',
	public $name_zh ="" ; //varchar(45) NOT NULL COMMENT '基本信息\n中文名',
	public $name_en ="" ; //varchar(100) DEFAULT NULL COMMENT '基本信息\n英文名',
	public $molecular_formula ="" ; //varchar(100) DEFAULT NULL COMMENT '基本信息\n分子式（需要额外的html标签用来显示上标和下标）\n下标：<sub>...</sub>\n上标：<sup>...</sup>',
	public $chemical_structure="" ; //mediumblob COMMENT '基本信息\n化学结构式，直接保存图片',
	public $molecular_weight="" ; //varchar(45) DEFAULT NULL COMMENT '基本信息\n分子量',
	public $CAS_registry_number="" ; //varchar(45) NOT NULL COMMENT '基本信息\nCAS号',
	public $classification="" ; //int(11) NOT NULL COMMENT '基本信息\n危险化学品分类\n使用int值表示不同危险等级，如下：\n1表示“重点环境管理危险化学品”\n2表示“一般危险化学品”\n3表示“非危险化学品”',
	public $appearance="" ; //varchar(100) DEFAULT NULL COMMENT '物化性质\n外观与性状',
	public $fusion_point="" ; //varchar(45) DEFAULT NULL COMMENT '物化性质\n熔点（℃）',
	public $boiling_point="" ; //varchar(45) DEFAULT NULL COMMENT '物化性质\n沸点（℃）',
	public $relative_density_water="" ; //varchar(45) DEFAULT NULL COMMENT '物化性质\n相对密度（g/mL）水=1',
	public $relative_density_air="" ; //varchar(45) DEFAULT NULL COMMENT '物化性质\n相对密度（g/mL）空气=1',
	public $saturated_vapor_pressure="" ; //varchar(45) DEFAULT NULL COMMENT '物化性质\n饱和蒸气压（kPa）',
	public $solubleness="" ; //varchar(100) DEFAULT NULL COMMENT '物化性质\n溶解性',
	public $combustibility="" ; //varchar(45) DEFAULT NULL COMMENT '物化性质\n燃烧性',
	public $flashing_point="" ; //varchar(45) DEFAULT NULL COMMENT '物化性质\n闪点（℃）',
	public $explosion_limit="" ; //varchar(45) DEFAULT NULL COMMENT '物化性质\n爆炸极限（v%或g/m3）',
	public $stability="" ; //varchar(45) DEFAULT NULL COMMENT '物化性质\n稳定性',
	public $extinguishant="" ; //varchar(100) DEFAULT NULL COMMENT '物化性质\n灭火剂',
	public $taboo="" ; //varchar(100) DEFAULT NULL COMMENT '物化性质\n禁忌物',
	public $ecology_col1="" ; //varchar(45) DEFAULT NULL COMMENT '生态性质\n生态毒性》急性水生生物毒性》急性毒性LC50/EC50（mg/L）',
	public $ecology_col2="" ; //varchar(45) DEFAULT NULL COMMENT '生态性质\n生态毒性》急性水生生物毒性》黑头呆鱼急性预测LC50（mg/L）',
	public $ecology_col3="" ; //varchar(45) DEFAULT NULL COMMENT '生态性质\n生态毒性》慢性水生生物毒性》慢性（≥28天）NOEC或ECx（mg/L）',
	public $ecology_col4="" ; //varchar(45) DEFAULT NULL COMMENT '生态性质\n生态毒性》慢性水生生物毒性》慢性预测',
	public $ecology_col5="" ; //varchar(45) DEFAULT NULL COMMENT '生态性质\n持久性和降解性》快速生物降解性》实测',
	public $ecology_col6="" ; //varchar(45) DEFAULT NULL COMMENT '生态性质\n持久性和降解性》快速生物降解性》预测',
	public $ecology_col7="" ; //varchar(45) DEFAULT NULL COMMENT '生态性质\n生物累积性》BCF》鱼类测量值',
	public $ecology_col8="" ; //varchar(45) DEFAULT NULL COMMENT '生态性质\n生物累积性》BCF》预测值',
	public $ecology_col9="" ; //varchar(45) DEFAULT NULL COMMENT '生态性质\n生物累积性》lgKow》测量值',
	public $ecology_col10="" ; //varchar(45) DEFAULT NULL COMMENT '生态性质\n生物累积性》lgKow》预测值',
	public $acute_toxicity="" ; //varchar(45) DEFAULT NULL COMMENT '健康效应\n急性毒性',
	public $skin_corrosion_stimulation="" ; //varchar(45) DEFAULT NULL COMMENT '健康效应\n皮肤腐蚀或刺激',
	public $eye_injury_stimulation="" ; //varchar(45) DEFAULT NULL COMMENT '健康效应\n眼损伤或刺激',
	public $sensitization="" ; //varchar(45) DEFAULT NULL COMMENT '健康效应\n呼吸或皮肤过敏',
	public $mutagenicity="" ; //varchar(45) DEFAULT NULL COMMENT '健康效应\n生殖细胞致突变性',
	public $carcinogenicity="" ; //varchar(45) DEFAULT NULL COMMENT '健康效应\n致癌性',
	public $reproductive_toxicity="" ; //varchar(45) DEFAULT NULL COMMENT '健康效应\n生殖毒性',
	public $systemic_toxicity="" ; //text COMMENT '健康效应\n特异性靶器官系统毒性',
	public $spill_response="" ; //text COMMENT '泄露处置',
	public $reference="" ; //text COMMENT '参考数据库\n参考链接之间使用“;”分隔',
}
?>